# Generated by Django 4.2.18 on 2025-02-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitcher', models.CharField(max_length=100)),
                ('platelocheight', models.FloatField(blank=True, null=True)),
                ('platelocside', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
