# Generated by Django 4.2.18 on 2025-02-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='updated',
        ),
    ]
