# Generated by Django 4.2.18 on 2025-02-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0002_remove_pitch_created_remove_pitch_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='pitchtype',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
