# Generated by Django 4.2.18 on 2025-02-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0003_pitch_pitchtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='velo',
            field=models.FloatField(default=0),
        ),
    ]
