# Generated by Django 4.2.18 on 2025-02-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0004_pitch_velo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='exitvelo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pitch',
            name='pitchcall',
            field=models.CharField(default='Nothing', max_length=100),
        ),
    ]
