# Generated by Django 4.2.18 on 2025-02-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0005_pitch_exitvelo_pitch_pitchcall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='exitvelo',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='pitchcall',
        ),
    ]
