# Generated by Django 4.2.18 on 2025-03-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0008_alter_pitch_exitspeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='exitspeed',
            field=models.FloatField(default=0),
        ),
    ]
