# Generated by Django 4.2.18 on 2025-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0009_alter_pitch_exitspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='batter',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='pitch',
            name='batter_team',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
