# Generated by Django 4.2.18 on 2025-03-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0010_pitch_batter_pitch_batter_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='playresult',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
