# Generated by Django 4.2.18 on 2025-03-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0011_pitch_playresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='korbb',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
